from typing import Any, Protocol, runtime_checkable

@runtime_checkable
class PoolProtocol(Protocol):
    def apply(self, func, args, kwds) -> Any: ...
    def apply_async(self, func, args, kwds, callback, error_callback) -> Any: ...
    def map(self, func, iterable, chunksize) -> Any: ...
    def map_async(self, func, iterable, chunksize, callback, error_callback) -> Any: ...
    def imap(self, func, iterable, chunksize) -> Any: ...
    def imap_unordered(self, func, iterable, chunksize) -> Any: ...
    def starmap(self, func, iterable, chunksize) -> Any: ...
    def starmap_async(self, func, iterable, chunksize, callback, error_callback) -> Any: ...
    def close(self) -> None: ...
    def terminate(self) -> None: ...
    def join(self) -> None: ...
